Vagrant.configure("2") do |config|

  config.vm.box = "generic/arch"

  config.vm.network "forwarded_port", guest: 8080, host: 3000,
    auto_correct: true

  config.vm.provision "shell", path: "provision/setup.sh", run: "always"

end
